apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"file-uploader:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"file-uploader\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: file-uploader
    app.kubernetes.io/component: file-uploader
    app.kubernetes.io/instance: file-uploader
    manager: kube-controller-manager
  name: file-uploader
  namespace: my-shared-storage
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: file-uploader
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: file-uploader
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/my-shared-storage/file-uploader:latest
        imagePullPolicy: IfNotPresent
        name: file-uploader
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/src/uploaded
          name: my-shared-storage
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            deployment: file-uploader
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            deployment: file-uploader
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - name: my-shared-storage
        persistentVolumeClaim:
          claimName: my-shared-storage
